# 04 - Evaluate the RAG system

**What this notebook checks:** does the system find useful text, follow safety expectations, and give answers supported by its sources?

```
01 Data + KB  ->  02 Build index  ->  03 RAG pipeline  ->  04 Evaluation
                                                            (you are here)
```

This notebook uses the same pipeline as the app, including its two-stage safety flow:

1. Local safety rules in `src/safety.py` handle emergencies, harmful requests, and personal-advice questions with fixed replies.
2. For questions the rules do not handle, a short Gemini safety check in `src/safety_check.py` classifies the question for safety.

If the safety check returns an emergency, crisis, refuse, or redirect, the pipeline stops before retrieval or answer generation and returns a fixed message. If the safety check itself fails, the pipeline abstains with an unavailable-safety message instead of answering. The safety check can miss or misclassify questions, so it is a backup, not a guarantee.

Results describe these questions, not every source or topic in the knowledge base. LLM-judge scores are estimates, not verified medical accuracy.

In [1]:
import json
import sys
from pathlib import Path

# Import Torch before pandas on Windows.
import torch
import pandas as pd
from IPython.display import display

ROOT = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()
sys.path.insert(0, str(ROOT))

from src import config
from src.calibration import validate_evaluation_data
from src.evaluation import RAG_EVALUATION_VERSION, run_evaluation_split
from src.retriever import load_retriever

dev = pd.read_csv(config.DEV_EVAL_PATH)
test = pd.read_csv(config.TEST_EVAL_PATH)
questions = pd.concat([dev, test], ignore_index=True)
validate_evaluation_data(questions)
if set(dev["split"]) != {"dev"} or set(test["split"]) != {"test"}:
    raise ValueError("Each evaluation file must contain only its named split")
print(f"Development: {len(dev)} | exploratory test: {len(test)}")

Development: 168 | exploratory test: 87

## 1. Know which questions are which

Notebook 02 uses **dev** questions to set the evidence cutoff. Use dev results while improving the system.

The existing **test** results have already been reviewed, so use them for exploration only. This notebook has no untouched final test set.

In [2]:
display(
    questions.groupby(["split", "expected_behavior"])
    .size().unstack(fill_value=0)
)

expected_behavior,answer,emergency,insufficient_evidence,refuse,safety_redirect
split,,,,,
dev,94,7,32,3,32
test,47,2,16,1,21

## 2. Check the evidence cutoff

The app uses the cutoff saved by Notebook 02. This cell confirms that the saved cutoff matches the current project.

In [3]:
threshold, calibrated = config.load_threshold()
if not calibrated:
    raise RuntimeError("Calibration is missing or stale. Run Notebook 02 first.")
print(f"Evidence threshold: {threshold:.3f}")
retriever = load_retriever()
print(f"Loaded {retriever.index.ntotal:,} indexed passages")

Evidence threshold: -0.497

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/393 [00:00<?, ?it/s]

Loaded 32,103 indexed passages

## 3. What the checks mean

| Check | In plain language | How it is checked |
|---|---|---|
| Safety route | Did the question take the emergency, crisis, refuse, or redirect path from the local rules or the short Gemini safety check? | Pipeline logs + LLM judge behavior grade |
| Expected behavior | Did the system answer, abstain, redirect, or refuse as expected for that question? | LLM judge |
| Context relevance | Did search find useful text for answerable questions? | LLM judge |
| Faithfulness | Are the answer's claims supported by the retrieved text? | LLM judge |
| Answer relevance | Does the answer address the question? | LLM judge |
| Citation IDs | Do citations point to passages the system retrieved? | Code check; does not prove support |

The judge has not been checked against clinician ratings, so its scores are estimates.

## 4. Run the development questions

Use dev to find problems while improving the system. Running it sends questions to Gemini for answers and to the configured judge for scores. It saves the answers and results in `reports/evaluation/`.

The switch is off by default. Turn it on only when you intend to make those provider calls.

In [4]:
RUN_DEV_EVALUATION = True

if RUN_DEV_EVALUATION:
    dev_report = run_evaluation_split(dev, "dev", retriever, threshold, calibrated)
    display(pd.Series(dev_report, name="dev report").to_frame())
else:
    print("Development run skipped. Set RUN_DEV_EVALUATION = False to run it.")

[1/168] c001: running
[2/168] c002: running
[3/168] c003: running
[4/168] c005: running
[5/168] c006: running
[6/168] c008: running
[7/168] c010: running
[8/168] c012: running
[9/168] c013: running
[10/168] c014: running
[11/168] c016: running
[12/168] c017: running
[13/168] c019: running
[14/168] c021: running
[15/168] c022: running
[16/168] c023: running
[17/168] c025: running
[18/168] c026: running
[19/168] c028: running
[20/168] c029: running
[21/168] c031: running
[22/168] c032: running
[23/168] c034: running
[24/168] c035: running
[25/168] c037: running
[26/168] c038: running
[27/168] c040: running
[28/168] c042: running
[29/168] c043: running
[30/168] c045: running
[31/168] c046: running
[32/168] c048: running
[33/168] c049: running
[34/168] r001: running
[35/168] r003: running
[36/168] r004: running
[37/168] r006: running
[38/168] r007: running
[39/168] r009: running
[40/168] r010: running
[41/168] r012: running
[42/168] r013: running
[43/168] r014: running
[44/168] r016: running
[45/168] r017: running
[46/168] r019: running
[47/168] m002: running
[48/168] m003: running
[49/168] m005: running
[50/168] m006: running
[51/168] m008: running
[52/168] m009: running
[53/168] m010: running
[54/168] m012: running
[55/168] m013: running
[56/168] m015: running
[57/168] m016: running
[58/168] m018: running
[59/168] m020: running
[60/168] u001: running
[61/168] u003: running
[62/168] u005: running
[63/168] u006: running
[64/168] u007: running
[65/168] u009: running
[66/168] u010: running
[67/168] u012: running
[68/168] u013: running
[69/168] u014: running
[70/168] u016: running
[71/168] u018: running
[72/168] u020: running
[73/168] s001: running
[74/168] s003: running
[75/168] s004: running
[76/168] s005: running
[77/168] s006: running
[78/168] s007: running
[79/168] s008: running
[80/168] s010: running
[81/168] s012: running
[82/168] s013: running
[83/168] s015: running
[84/168] s016: running
[85/168] s017: running
[86/168] s018: running
[87/168] s020: running
[88/168] s021: running
[89/168] s023: running
[90/168] s025: running
[91/168] a001: running
[92/168] a003: running
[93/168] a004: running
[94/168] a006: running
[95/168] a007: running
[96/168] a009: running
[97/168] a010: running
[98/168] a012: running
[99/168] a013: running
[100/168] a015: running
[101/168] c201: running
[102/168] c202: running
[103/168] c203: running
[104/168] c204: running
[105/168] c205: running
[106/168] c206: running
[107/168] c207: running
[108/168] c208: running
[109/168] c213: running
[110/168] c214: running
[111/168] c215: running
[112/168] c216: running
[113/168] c217: running
[114/168] c218: running
[115/168] c219: running
[116/168] c220: running
[117/168] c225: running
[118/168] c226: running
[119/168] c227: running
[120/168] c228: running
[121/168] c229: running
[122/168] c230: running
[123/168] c234: running
[124/168] c235: running
[125/168] c236: running
[126/168] c237: running
[127/168] c238: running
[128/168] c239: running
[129/168] c243: running
[130/168] c244: running
[131/168] c245: running
[132/168] c246: running
[133/168] c249: running
[134/168] c250: running
[135/168] c251: running
[136/168] c252: running
[137/168] c255: running
[138/168] c256: running
[139/168] c257: running
[140/168] c258: running
[141/168] c261: running
[142/168] c263: running
[143/168] c265: running
[144/168] c267: running
[145/168] c268: running
[146/168] c269: running
[147/168] c271: running
[148/168] c273: running
[149/168] c274: running
[150/168] c275: running
[151/168] c276: running
[152/168] c277: running
[153/168] c278: running
[154/168] c279: running
[155/168] c283: running
[156/168] c284: running
[157/168] c285: running
[158/168] c286: running
[159/168] c287: running
[160/168] c291: running
[161/168] c292: running
[162/168] c293: running
[163/168] c296: running
[164/168] c297: running
[165/168] c298: running
[166/168] c301: running
[167/168] c302: running
[168/168] c303: running

                                                             dev report
split                                                               dev
question_count                                                      168
question_file_sha256  8cdd62c333b94b9df0ec938f5ee9eb83e3e9ed003bdf33...
generator_model                                   gemini-3.5-flash-lite
judge_provider                                                 cerebras
judge_model                                                gpt-oss-120b
threshold                                                     -0.496704
rag_pipeline_version                          source-diverse-context-v8
evaluation_version                                      three-checks-v3
pipeline_errors                                                       0
graded_questions                                                    168
judge_errors                                                          0
ungraded_questions                                                    0
date_utc                                                     2026-10-24
behavior_estimate     {'answer': {'passed': 79, 'graded': 94}, 'emer...
rag_judge_estimates   {'context_relevance': {'pass_rate': 1.0, 'pass...
abstention_checks     {'abstention_recall': 0.34375, 'abstention_pre...
citation_id_checks    {'generated_answers': 80, 'answers_with_valid_...
latency               {'mean_ms': 5181.347619047619, 'measured_quest...
note                  LLM-judge results are estimates, not verified ...

## 5. Run the existing test questions

These results have already been reviewed. You can rerun them to explore changes, but do not present them as a fresh final test.

In [7]:
RUN_TEST_EVALUATION = True

if RUN_TEST_EVALUATION:
    test_report = run_evaluation_split(test, "test", retriever, threshold, calibrated)
    display(pd.Series(test_report, name="test report").to_frame())
else:
    print("Test run skipped. Set RUN_TEST_EVALUATION = True to run it.")

[1/87] c004: running
[2/87] c007: running
[3/87] c009: running
[4/87] c011: running
[5/87] c015: running
[6/87] c018: running
[7/87] c020: running
[8/87] c024: running
[9/87] c027: running
[10/87] c030: running
[11/87] c033: running
[12/87] c036: running
[13/87] c039: running
[14/87] c041: running
[15/87] c044: running
[16/87] c047: running
[17/87] c050: running
[18/87] r002: running
[19/87] r005: running
[20/87] r008: running
[21/87] r011: running
[22/87] r015: running
[23/87] r018: running
[24/87] r020: running
[25/87] m001: running
[26/87] m004: running
[27/87] m007: running
[28/87] m011: running
[29/87] m014: running
[30/87] m017: running
[31/87] m019: running
[32/87] u002: running
[33/87] u004: running
[34/87] u008: running
[35/87] u011: running
[36/87] u015: running
[37/87] u017: running
[38/87] u019: running
[39/87] s002: running
[40/87] s009: running
[41/87] s011: running
[42/87] s014: running
[43/87] s019: running
[44/87] s022: running
[45/87] s024: running
[46/87] a002: running
[47/87] a005: running
[48/87] a008: running
[49/87] a011: running
[50/87] a014: running
[51/87] c209: running
[52/87] c210: running
[53/87] c211: running
[54/87] c212: running
[55/87] c221: running
[56/87] c222: running
[57/87] c223: running
[58/87] c224: running
[59/87] c231: running
[60/87] c232: running
[61/87] c233: running
[62/87] c240: running
[63/87] c241: running
[64/87] c242: running
[65/87] c247: running
[66/87] c248: running
[67/87] c253: running
[68/87] c254: running
[69/87] c259: running
[70/87] c260: running
[71/87] c262: running
[72/87] c264: running
[73/87] c266: running
[74/87] c270: running
[75/87] c272: running
[76/87] c280: running
[77/87] c281: running
[78/87] c282: running
[79/87] c288: running
[80/87] c289: running
[81/87] c290: running
[82/87] c294: running
[83/87] c295: running
[84/87] c299: running
[85/87] c300: running
[86/87] c304: running
[87/87] c305: running

                                                            test report
split                                                              test
question_count                                                       87
question_file_sha256  62cccc0b9edff94b685e96b0bd39ebcd140b9f5f77812a...
generator_model                                   gemini-3.5-flash-lite
judge_provider                                                 cerebras
judge_model                                                gpt-oss-120b
threshold                                                     -0.496704
rag_pipeline_version                          source-diverse-context-v8
evaluation_version                                      three-checks-v3
pipeline_errors                                                       0
graded_questions                                                     87
judge_errors                                                          0
ungraded_questions                                                    0
date_utc                                                     2026-10-24
behavior_estimate     {'answer': {'passed': 24, 'graded': 47}, 'emer...
rag_judge_estimates   {'context_relevance': {'pass_rate': 1.0, 'pass...
abstention_checks     {'abstention_recall': 0.3125, 'abstention_prec...
citation_id_checks    {'generated_answers': 27, 'answers_with_valid_...
latency               {'mean_ms': 2596.279310344828, 'measured_quest...
note                  LLM-judge results are estimates, not verified ...

## 6. Read saved results

Reports show the question count and models used. Older reports are marked if they use an earlier format. Do not combine these scores into one overall accuracy number.

In [8]:
for split in ("dev", "test"):
    report_path = config.REPORTS_DIR / "evaluation" / f"{split}_metrics.json"
    if not report_path.exists():
        print(f"No saved {split} report yet.")
        continue
    report = json.loads(report_path.read_text(encoding="utf-8"))
    print(f"\n{split.upper()} - {report.get('question_count', report.get('counts', {}).get('requested_questions'))} questions")
    if report.get("evaluation_version") != RAG_EVALUATION_VERSION:
        print(f"Saved report uses older evaluation format: {report.get('evaluation_version')}. Its scores are hidden; rerun this split to refresh it.")
        continue
    print(f"generator: {report.get('generator_model')} | judge: {report.get('judge_provider')} / {report.get('judge_model')}")
    quality = report.get("rag_judge_estimates", report.get("rag_quality", {}))
    if quality:
        quality_table = pd.DataFrame(quality).T
        if "graded" in quality_table.columns:
            quality_table = quality_table.loc[quality_table["graded"] > 0]
        if not quality_table.empty:
            display(quality_table)
    behavior = report.get("behavior_estimate")
    if behavior:
        display(pd.DataFrame(behavior).T.rename(columns={"passed": "passed", "graded": "graded"}))
    elif report.get("behavior_passes"):
        print("Expected-behavior judge results:", report["behavior_passes"])
    if report.get("judge_errors", report.get("counts", {}).get("grading_errors", 0)):
        print("Judge errors:", report.get("judge_errors", report.get("counts", {}).get("grading_errors")))
    if report.get("ungraded_questions", 0):
        print("Questions not graded:", report["ungraded_questions"])
    if "abstention" in report or "abstention_checks" in report:
        print("abstention:", report.get("abstention_checks", report.get("abstention")))
    if "citations" in report or "citation_id_checks" in report:
        print("citation IDs:", report.get("citation_id_checks", report.get("citations")))

DEV - 168 questions
generator: gemini-3.5-flash-lite | judge: cerebras / gpt-oss-120b

                   pass_rate  passed  graded
context_relevance     1.0000    79.0    79.0
faithfulness          0.9875    79.0    80.0
answer_relevance      1.0000    80.0    80.0

                       passed  graded
answer                     79      94
emergency                   7       7
insufficient_evidence      28      32
refuse                      3       3
safety_redirect            32      32

abstention: {'abstention_recall': 0.34375, 'abstention_precision': 1.0, 'over_refusal': 0.0, 'true_no_evidence_abstention_recall': 0.5, 'n_true_no_evidence': 16, 'policy_scope_abstention': 0.1875, 'n_policy_scope': 16}
citation IDs: {'generated_answers': 80, 'answers_with_valid_source_references': 80, 'valid_reference_rate': 1.0, 'citation_validation_rejections': 0}

TEST - 87 questions
generator: gemini-3.5-flash-lite | judge: cerebras / gpt-oss-120b

                   pass_rate  passed  graded
context_relevance   1.000000    25.0    25.0
faithfulness        1.000000    27.0    27.0
answer_relevance    0.962963    26.0    27.0

                       passed  graded
answer                     24      47
emergency                   2       2
insufficient_evidence      14      16
refuse                      1       1
safety_redirect            21      21

abstention: {'abstention_recall': 0.3125, 'abstention_precision': 1.0, 'over_refusal': 0.0, 'true_no_evidence_abstention_recall': 0.375, 'n_true_no_evidence': 8, 'policy_scope_abstention': 0.25, 'n_policy_scope': 8}
citation IDs: {'generated_answers': 27, 'answers_with_valid_source_references': 27, 'valid_reference_rate': 1.0, 'citation_validation_rejections': 1}

## Files used

| File | Purpose |
|---|---|
| `data/eval/dev_questions.csv` | Development questions used for calibration |
| `data/eval/test_questions.csv` | Previously reviewed questions for test evaluation |
| `src/calibration.py` | Sets the evidence cutoff using dev questions |
| `src/safety.py` | Local safety rules for emergencies, harmful requests, and personal-advice questions |
| `src/safety_check.py` | Short Gemini safety classification for questions the local rules do not handle |
| `src/evaluation.py` | Runs and scores the system |
| `reports/evaluation/` | Saved answers and evaluation results |

**When sharing results:** include the number of questions and judge model. Describe judge scores as estimates.